name: Mirror Data Directory

on:
  schedule:
    # Run every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  mirror-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Print UTC time (debug)
        run: date -u
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml
          
      - name: Run mirror script
        run: python mirror_data.py
        
      - name: Check if mirror was successful
        run: |
          if [ -f "mirror_status.txt" ]; then
            status=$(cat mirror_status.txt)
            if [ "$status" = "FAILED" ]; then
              echo "Mirror failed - not committing changes"
              exit 0
            fi
          fi
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add data/
          if ! git diff --staged --quiet; then
            git commit -m "Data backup: $(date '+%Y-%m-%d %H:%M:%S UTC')"
            git push
          else
            echo "No changes to commit"
          fi
