name: Test Schedule

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes (more reliable than 2 min)
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Debug info
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Time: $(date)"
          echo "This is a test of scheduled workflows"
